# Generated by Django 4.2.3 on 2023-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshop', '0002_newcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='shop/media')),
                ('desc', models.CharField(max_length=300)),
                ('pub_data', models.DateField()),
            ],
        ),
    ]
