# Generated by Django 4.2.3 on 2023-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshop', '0008_cartuserdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
    ]
