# Generated by Django 4.2.5 on 2023-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshop', '0009_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
